[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
disconnectedSessionTTL = 600

[browser]
serverAddress = "coletti2.streamlit.app"
serverPort = 443

[client]
showErrorDetails = false

[theme]
base = "light"
